/**
 * الوحدة 8: قائمة تصدير التقرير — تظهر بمجرد جاهزية البيانات (بلا اشتراط تثبيت استنتاجات).
 * كل خيار في القائمة يبدأ التصدير مباشرة بضغطة واحدة، وبلا أي نافذة تأكيد.
 */
import { useEffect, useRef, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { ChevronDown, Download, FileDown, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ReportDocument, type ReportData } from "@/components/ReportDocument";
import { buildReportPdf, downloadPdfBlob } from "@/lib/pdf-report";
import { REPORT_VARIANTS, reportFileName, type PinnedInsight, type ReportVariant } from "@/lib/report";
import { generateAutoInsights } from "@/lib/auto-insights";
import { planAiQuery } from "@/lib/ai-query.functions";
import type { TableInfo } from "@/lib/duckdb-service";
import type { HealthReport } from "@/lib/data-health";
import type { Row } from "@/lib/parse-file";

interface Props {
  fileName: string;
  health: HealthReport | null;
  rowCount: number;
  columnCount: number;
  cleanSteps: ReportData["cleanSteps"];
  insights: PinnedInsight[];
  tableInfo: TableInfo | null;
  sample: Row[];
  /** جاهزية البيانات: الجدول محمَّل وفحص الجودة انتهى. */
  ready: boolean;
}

type Phase = "idle" | "analyzing" | "rendering";

interface PreviewState {
  url: string;
  blob: Blob;
  fileName: string;
  label: string;
}

export function ReportExportButton(props: Props) {
  const askAi = useServerFn(planAiQuery);
  const [phase, setPhase] = useState<Phase>("idle");
  const [error, setError] = useState<string | null>(null);
  const [doc, setDoc] = useState<ReportData | null>(null);
  const [preview, setPreview] = useState<PreviewState | null>(null);
  const previewRef = useRef<PreviewState | null>(null);
  previewRef.current = preview;

  // تحرير رابط المعاينة عند إزالة المكوّن.
  useEffect(() => {
    return () => {
      if (previewRef.current) URL.revokeObjectURL(previewRef.current.url);
    };
  }, []);

  if (!props.ready) return null;
  const busy = phase !== "idle";

  function closePreview() {
    setPreview((p) => {
      if (p) URL.revokeObjectURL(p.url);
      return null;
    });
  }

  async function run(variant: ReportVariant) {
    if (busy) return;
    setError(null);
    closePreview();
    const meta = REPORT_VARIANTS.find((v) => v.id === variant)!;
    let insights = props.insights;

    try {
      // توليد تلقائي فقط عند الحاجة — الأسلوب المختصر لا يستدعي الذكاء الاصطناعي إطلاقاً.
      if (meta.needsInsights && insights.length === 0 && props.tableInfo) {
        setPhase("analyzing");
        insights = await generateAutoInsights({
          askAi,
          tableInfo: props.tableInfo,
          sample: props.sample,
          health: props.health,
        });
        if (insights.length === 0) {
          setError("تعذّر توليد استنتاجات تلقائية. جرّب التقرير المختصر أو ثبّت استنتاجاً.");
          setPhase("idle");
          return;
        }
      }

      setPhase("rendering");
      const date = new Date();
      const autoGenerated = insights !== props.insights;
      setDoc({
        fileName: props.fileName,
        health: props.health,
        rowCount: props.rowCount,
        columnCount: props.columnCount,
        cleanSteps: props.cleanSteps,
        insights,
        date,
        variant,
        autoGenerated,
      });

      // انتظار رسم المستند خارج الشاشة (الرسوم البيانية تحتاج إطاراً إضافياً).
      await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(() => r(null))));
      await new Promise((r) => setTimeout(r, 350));
      const root = document.getElementById("basira-report-root");
      if (!root) throw new Error("no-root");
      const blob = await buildReportPdf(root);
      setPreview({
        blob,
        url: URL.createObjectURL(blob),
        fileName: reportFileName(props.fileName, date),
        label: meta.label,
      });
    } catch {
      setError("تعذّر إنشاء التقرير، حاول مرة أخرى.");
    } finally {
      setDoc(null);
      setPhase("idle");
    }
  }

  return (
    <>
      <div className="flex flex-col items-end gap-1">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button type="button" disabled={busy} className="clay-press h-10 gap-2 rounded-xl px-4">
              {busy ? (
                <Loader2 className="size-4 animate-spin" strokeWidth={2} />
              ) : (
                <FileDown className="size-4" strokeWidth={2} />
              )}
              {phase === "analyzing"
                ? "جاري تحليل البيانات..."
                : phase === "rendering"
                  ? "جاري إنشاء التقرير..."
                  : "تصدير تقرير PDF"}
              {!busy && <ChevronDown className="size-4 opacity-70" strokeWidth={2} />}
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-64">
            {REPORT_VARIANTS.map((v) => (
              <DropdownMenuItem
                key={v.id}
                onSelect={() => void run(v.id)}
                className="flex-col items-start gap-0.5 py-2"
              >
                <span className="text-sm font-medium">{v.label}</span>
                <span className="text-xs text-muted-foreground">{v.description}</span>
              </DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
        {error && <span className="max-w-[260px] text-end text-[11px] text-destructive">{error}</span>}
      </div>

      {doc && (
        <div
          id="basira-report-root"
          aria-hidden
          style={{ position: "fixed", top: 0, insetInlineStart: -20000, zIndex: -1, pointerEvents: "none" }}
        >
          <ReportDocument data={doc} />
        </div>
      )}

      <Dialog open={preview !== null} onOpenChange={(open) => !open && closePreview()}>
        <DialogContent
          dir="rtl"
          className="flex h-[90vh] max-w-5xl flex-col gap-4 rounded-2xl p-5 sm:max-w-5xl"
        >
          <DialogHeader className="text-start">
            <DialogTitle className="font-display text-lg">معاينة التقرير — {preview?.label}</DialogTitle>
            <DialogDescription className="text-xs">
              تصفّح التقرير قبل تنزيله. المعاينة تُولَّد محلياً داخل متصفحك.
            </DialogDescription>
          </DialogHeader>

          {preview && (
            <iframe
              key={preview.url}
              src={`${preview.url}#toolbar=0&view=FitH`}
              title="معاينة تقرير PDF"
              className="min-h-0 w-full flex-1 rounded-xl border border-border/70 bg-background"
            />
          )}

          <div className="flex flex-wrap items-center justify-between gap-2">
            <span dir="ltr" className="truncate font-mono text-[11px] text-muted-foreground">
              {preview?.fileName}
            </span>
            <div className="flex gap-2">
              <Button type="button" variant="secondary" className="clay-press rounded-xl" onClick={closePreview}>
                إغلاق
              </Button>
              <Button
                type="button"
                className="clay-press gap-2 rounded-xl"
                onClick={() => preview && downloadPdfBlob(preview.blob, preview.fileName)}
              >
                <Download className="size-4" strokeWidth={2} />
                تنزيل PDF
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
