/**
 * الوحدة 8: قائمة تصدير التقرير — تظهر بمجرد جاهزية البيانات (بلا اشتراط تثبيت استنتاجات).
 * كل خيار يفتح معاينة مباشرة للتقرير داخل المتصفح، والتنزيل يتم من داخل المعاينة.
 */
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { ChevronDown, Download, FileDown, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { PAGE_H, PAGE_W, ReportDocument, type ReportData } from "@/components/ReportDocument";
import { buildReportPdf, downloadPdfBlob } from "@/lib/pdf-report";
import { REPORT_VARIANTS, reportFileName, type PinnedInsight, type ReportVariant } from "@/lib/report";
import { generateAutoInsights } from "@/lib/auto-insights";
import { DATA_EXPORTS, exportCsv, exportXlsx, type DataExportFormat } from "@/lib/data-export";
import { planAiQuery } from "@/lib/ai-query.functions";
import type { TableInfo } from "@/lib/duckdb-service";
import type { HealthReport } from "@/lib/data-health";
import type { Row } from "@/lib/parse-file";

interface Props {
  fileName: string;
  health: HealthReport | null;
  rowCount: number;
  columnCount: number;
  cleanSteps: ReportData["cleanSteps"];
  insights: PinnedInsight[];
  tableInfo: TableInfo | null;
  sample: Row[];
  /** جاهزية البيانات: الجدول محمَّل وفحص الجودة انتهى. */
  ready: boolean;
}

type Phase = "idle" | "analyzing" | "preparing" | "downloading" | "exporting";

/** عرض المعاينة داخل النافذة (صفحة A4 مصغّرة بنسبة ثابتة). */
const PREVIEW_SCALE = 0.62;

export function ReportExportButton(props: Props) {
  const askAi = useServerFn(planAiQuery);
  const [phase, setPhase] = useState<Phase>("idle");
  const [error, setError] = useState<string | null>(null);
  const [doc, setDoc] = useState<ReportData | null>(null);
  const [label, setLabel] = useState("");

  if (!props.ready) return null;
  const busy = phase !== "idle";
  const fileName = doc ? reportFileName(props.fileName, doc.date) : "";

  async function run(variant: ReportVariant) {
    if (busy) return;
    setError(null);
    setDoc(null);
    const meta = REPORT_VARIANTS.find((v) => v.id === variant)!;
    let insights = props.insights;

    try {
      // توليد تلقائي فقط عند الحاجة — الأسلوب المختصر لا يستدعي الذكاء الاصطناعي إطلاقاً.
      if (meta.needsInsights && insights.length === 0 && props.tableInfo) {
        setPhase("analyzing");
        insights = await generateAutoInsights({
          askAi,
          tableInfo: props.tableInfo,
          sample: props.sample,
          health: props.health,
        });
        if (insights.length === 0) {
          setError("تعذّر توليد استنتاجات تلقائية. جرّب التقرير المختصر أو ثبّت استنتاجاً.");
          setPhase("idle");
          return;
        }
      }

      setPhase("preparing");
      setLabel(meta.label);
      setDoc({
        fileName: props.fileName,
        health: props.health,
        rowCount: props.rowCount,
        columnCount: props.columnCount,
        cleanSteps: props.cleanSteps,
        insights,
        date: new Date(),
        variant,
        autoGenerated: insights !== props.insights,
      });
    } catch {
      setError("تعذّر إنشاء التقرير، حاول مرة أخرى.");
      setDoc(null);
    } finally {
      setPhase((p) => (p === "analyzing" ? "idle" : p === "preparing" ? "idle" : p));
    }
  }

  async function download() {
    if (!doc || phase === "downloading") return;
    setPhase("downloading");
    try {
      const root = document.getElementById("basira-report-root");
      if (!root) throw new Error("no-root");
      // إمهال إطار إضافي لضمان اكتمال رسم المخططات قبل التصوير.
      await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(() => r(null))));
      const blob = await buildReportPdf(root);
      downloadPdfBlob(blob, fileName);
    } catch {
      setError("تعذّر إنشاء ملف PDF، حاول مرة أخرى.");
    } finally {
      setPhase("idle");
    }
  }

  /** تصدير البيانات نفسها (CSV / Excel) مباشرة بلا معاينة. */
  async function runDataExport(format: DataExportFormat) {
    if (busy) return;
    setError(null);
    setPhase("exporting");
    try {
      const ctx = {
        fileName: props.fileName,
        columns: props.tableInfo?.schema.map((c) => c.name) ?? [],
        health: props.health,
        cleanSteps: props.cleanSteps,
        insights: props.insights,
      };
      if (format === "csv") await exportCsv(ctx);
      else await exportXlsx(ctx);
    } catch {
      setError("تعذّر تصدير البيانات، حاول مرة أخرى.");
    } finally {
      setPhase("idle");
    }
  }

  async function downloadUnused() {
    if (!doc || phase === "downloading") return;
    setPhase("downloading");
    try {
      const root = document.getElementById("basira-report-root");
      if (!root) throw new Error("no-root");
      // إمهال إطار إضافي لضمان اكتمال رسم المخططات قبل التصوير.
      await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(() => r(null))));
      const blob = await buildReportPdf(root);
      downloadPdfBlob(blob, fileName);
    } catch {
      setError("تعذّر إنشاء ملف PDF، حاول مرة أخرى.");
    } finally {
      setPhase("idle");
    }
  }

  return (
    <>
      <div className="flex flex-col items-end gap-1">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button type="button" disabled={busy} className="clay-press h-10 gap-2 rounded-xl px-4">
              {busy ? (
                <Loader2 className="size-4 animate-spin" strokeWidth={2} />
              ) : (
                <FileDown className="size-4" strokeWidth={2} />
              )}
              {phase === "analyzing"
                ? "جاري تحليل البيانات..."
                : phase === "preparing"
                  ? "جاري تجهيز المعاينة..."
                  : "تصدير تقرير PDF"}
              {!busy && <ChevronDown className="size-4 opacity-70" strokeWidth={2} />}
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-64">
            {REPORT_VARIANTS.map((v) => (
              <DropdownMenuItem
                key={v.id}
                onSelect={() => void run(v.id)}
                className="flex-col items-start gap-0.5 py-2"
              >
                <span className="text-sm font-medium">{v.label}</span>
                <span className="text-xs text-muted-foreground">{v.description}</span>
              </DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
        {error && <span className="max-w-[260px] text-end text-[11px] text-destructive">{error}</span>}
      </div>

      <Dialog open={doc !== null} onOpenChange={(open) => !open && phase !== "downloading" && setDoc(null)}>
        <DialogContent
          dir="rtl"
          className="flex h-[92vh] max-w-[min(94vw,900px)] flex-col gap-4 rounded-2xl p-5 sm:max-w-[min(94vw,900px)]"
        >
          <DialogHeader className="text-start">
            <DialogTitle className="font-display text-lg">معاينة التقرير — {label}</DialogTitle>
            <DialogDescription className="text-xs">
              هذه معاينة مطابقة لصفحات ملف PDF، تُولَّد محلياً داخل متصفحك قبل التنزيل.
            </DialogDescription>
          </DialogHeader>

          {/* حاوية التمرير: المستند نفسه هو مصدر التصوير عند التنزيل. */}
          <div className="min-h-0 flex-1 overflow-auto rounded-xl border border-border/70 bg-background/60 p-4">
            {doc && (
              <div
                className="mx-auto"
                style={{ width: PAGE_W * PREVIEW_SCALE }}
              >
                <div
                  id="basira-report-root"
                  className="[&_[data-pdf-page]]:mb-5 [&_[data-pdf-page]]:rounded-lg [&_[data-pdf-page]]:shadow-[var(--shadow-clay)]"
                  style={{
                    width: PAGE_W,
                    transform: `scale(${PREVIEW_SCALE})`,
                    transformOrigin: "top center",
                    marginBottom: -(PAGE_H * (1 - PREVIEW_SCALE)),
                  }}
                >
                  <ReportDocument data={doc} />
                </div>
              </div>
            )}
          </div>

          <div className="flex flex-wrap items-center justify-between gap-2">
            <span dir="ltr" className="truncate font-mono text-[11px] text-muted-foreground">
              {fileName}
            </span>
            <div className="flex gap-2">
              <Button
                type="button"
                variant="secondary"
                className="clay-press rounded-xl"
                disabled={phase === "downloading"}
                onClick={() => setDoc(null)}
              >
                إغلاق
              </Button>
              <Button
                type="button"
                className="clay-press gap-2 rounded-xl"
                disabled={phase === "downloading"}
                onClick={() => void download()}
              >
                {phase === "downloading" ? (
                  <Loader2 className="size-4 animate-spin" strokeWidth={2} />
                ) : (
                  <Download className="size-4" strokeWidth={2} />
                )}
                {phase === "downloading" ? "جاري إنشاء الملف..." : "تنزيل PDF"}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
