/**
 * الوحدة 8: قائمة تصدير التقرير — تظهر بمجرد جاهزية البيانات (بلا اشتراط تثبيت استنتاجات).
 * كل خيار في القائمة يبدأ التصدير مباشرة بضغطة واحدة، وبلا أي نافذة تأكيد.
 */
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { ChevronDown, FileDown, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { ReportDocument, type ReportData } from "@/components/ReportDocument";
import { exportReportPdf } from "@/lib/pdf-report";
import { REPORT_VARIANTS, reportFileName, type PinnedInsight, type ReportVariant } from "@/lib/report";
import { generateAutoInsights } from "@/lib/auto-insights";
import { planAiQuery } from "@/lib/ai-query.functions";
import type { TableInfo } from "@/lib/duckdb-service";
import type { HealthReport } from "@/lib/data-health";
import type { Row } from "@/lib/parse-file";

interface Props {
  fileName: string;
  health: HealthReport | null;
  rowCount: number;
  columnCount: number;
  cleanSteps: ReportData["cleanSteps"];
  insights: PinnedInsight[];
  tableInfo: TableInfo | null;
  sample: Row[];
  /** جاهزية البيانات: الجدول محمَّل وفحص الجودة انتهى. */
  ready: boolean;
}

type Phase = "idle" | "analyzing" | "rendering";

export function ReportExportButton(props: Props) {
  const askAi = useServerFn(planAiQuery);
  const [phase, setPhase] = useState<Phase>("idle");
  const [error, setError] = useState<string | null>(null);
  const [doc, setDoc] = useState<ReportData | null>(null);

  if (!props.ready) return null;
  const busy = phase !== "idle";

  async function run(variant: ReportVariant) {
    if (busy) return;
    setError(null);
    const meta = REPORT_VARIANTS.find((v) => v.id === variant)!;
    let insights = props.insights;

    try {
      // توليد تلقائي فقط عند الحاجة — الأسلوب المختصر لا يستدعي الذكاء الاصطناعي إطلاقاً.
      if (meta.needsInsights && insights.length === 0 && props.tableInfo) {
        setPhase("analyzing");
        insights = await generateAutoInsights({
          askAi,
          tableInfo: props.tableInfo,
          sample: props.sample,
          health: props.health,
        });
        if (insights.length === 0) {
          setError("تعذّر توليد استنتاجات تلقائية. جرّب التقرير المختصر أو ثبّت استنتاجاً.");
          setPhase("idle");
          return;
        }
      }

      setPhase("rendering");
      const date = new Date();
      const autoGenerated = insights !== props.insights;
      setDoc({
        fileName: props.fileName,
        health: props.health,
        rowCount: props.rowCount,
        columnCount: props.columnCount,
        cleanSteps: props.cleanSteps,
        insights,
        date,
        variant,
        autoGenerated,
      });

      // انتظار رسم المستند خارج الشاشة (الرسوم البيانية تحتاج إطاراً إضافياً).
      await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(() => r(null))));
      await new Promise((r) => setTimeout(r, 350));
      const root = document.getElementById("basira-report-root");
      if (!root) throw new Error("no-root");
      await exportReportPdf(root, reportFileName(props.fileName, date));
    } catch {
      setError("تعذّر إنشاء التقرير، حاول مرة أخرى.");
    } finally {
      setDoc(null);
      setPhase("idle");
    }
  }

  return (
    <>
      <div className="flex flex-col items-end gap-1">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button type="button" disabled={busy} className="clay-press h-10 gap-2 rounded-xl px-4">
              {busy ? (
                <Loader2 className="size-4 animate-spin" strokeWidth={2} />
              ) : (
                <FileDown className="size-4" strokeWidth={2} />
              )}
              {phase === "analyzing"
                ? "جاري تحليل البيانات..."
                : phase === "rendering"
                  ? "جاري إنشاء التقرير..."
                  : "تصدير تقرير PDF"}
              {!busy && <ChevronDown className="size-4 opacity-70" strokeWidth={2} />}
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-64">
            {REPORT_VARIANTS.map((v) => (
              <DropdownMenuItem
                key={v.id}
                onSelect={() => void run(v.id)}
                className="flex-col items-start gap-0.5 py-2"
              >
                <span className="text-sm font-medium">{v.label}</span>
                <span className="text-xs text-muted-foreground">{v.description}</span>
              </DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
        {error && <span className="max-w-[260px] text-end text-[11px] text-destructive">{error}</span>}
      </div>

      {doc && (
        <div
          id="basira-report-root"
          aria-hidden
          style={{ position: "fixed", top: 0, insetInlineStart: -20000, zIndex: -1, pointerEvents: "none" }}
        >
          <ReportDocument data={doc} />
        </div>
      )}
    </>
  );
}
