/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevReportTestRouteImport } from './routes/dev.report-test'
import { Route as DevSqlValidatorTestRouteImport } from './routes/dev.sql-validator-test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevReportTestRoute = DevReportTestRouteImport.update({
  id: '/dev/report-test',
  path: '/dev/report-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSqlValidatorTestRoute = DevSqlValidatorTestRouteImport.update({
  id: '/dev/sql-validator-test',
  path: '/dev/sql-validator-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/report-test': typeof DevReportTestRoute
  '/dev/sql-validator-test': typeof DevSqlValidatorTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/report-test': typeof DevReportTestRoute
  '/dev/sql-validator-test': typeof DevSqlValidatorTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/report-test': typeof DevReportTestRoute
  '/dev/sql-validator-test': typeof DevSqlValidatorTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/report-test' | '/dev/sql-validator-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/report-test' | '/dev/sql-validator-test'
  id: '__root__' | '/' | '/dev/report-test' | '/dev/sql-validator-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevReportTestRoute: typeof DevReportTestRoute
  DevSqlValidatorTestRoute: typeof DevSqlValidatorTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/report-test': {
      id: '/dev/report-test'
      path: '/dev/report-test'
      fullPath: '/dev/report-test'
      preLoaderRoute: typeof DevReportTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/sql-validator-test': {
      id: '/dev/sql-validator-test'
      path: '/dev/sql-validator-test'
      fullPath: '/dev/sql-validator-test'
      preLoaderRoute: typeof DevSqlValidatorTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevReportTestRoute: DevReportTestRoute,
  DevSqlValidatorTestRoute: DevSqlValidatorTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
